link_tags_urls:
  - https://fonts.googleapis.com/css2?family=Barlow:wght@200;300;400;500;600&display=swap
user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
